version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
    networks:
      - my-network
    runtime: nvidia
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
    stdin_open: true

  app:
    build:
      context: ./app
    stdin_open: true
    tty: true
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

    ports:
      - "12312:12312"

    depends_on:
      - ollama

    networks:
      - my-network

    volumes:
      - ./app:/app

networks:
  my-network:
    driver: bridge
