version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
    networks:
      - my-network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

  app:
    build:
      context: ./app
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_BASE_URL=http://ollama:11434

    ports:
      - "8000:8000"

    depends_on:
      - ollama

    networks:
      - my-network

    volumes:
      - ./app/src:/app/src # TODO A retirer à la fin, quand j'aurais fini de developper, permis de changer le code du container directement depuis vscode.

networks:
  my-network:
    driver: bridge
